# Generated by Django 5.0.7 on 2024-07-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guitarras_acusticas',
            new_name='Acustica',
        ),
        migrations.RenameModel(
            old_name='Amplificadores',
            new_name='Amplificadore',
        ),
        migrations.RenameModel(
            old_name='Efectos',
            new_name='Efecto',
        ),
        migrations.RenameModel(
            old_name='Guitarras_electricas',
            new_name='Electrica',
        ),
    ]
